spring.application.name=shoping-cart-mcp

# -------------------------------
# PostgreSQL Datasource (via pgAdmin)
# -------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/mcp_demo
spring.datasource.username=postgres 
spring.datasource.password=root 
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------
# JPA & Hibernate
# -------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -------------------------------
# MCP Server Configuration
# -------------------------------
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.stdio=true
spring.ai.mcp.server.name=shopping-cart-server
spring.ai.mcp.server.version=1.0.0

# -------------------------------
# Logging & Banner
# -------------------------------
spring.main.banner-mode=off
logging.file.name=./mcp-server/target/server.log

